# Laboratorio de regresión - 3

## Significancia de factores

|                |   |
:----------------|---|
| Francisco Josué Ramírez Avila      |   |
| 25/08/2025     |   |
| 747819 |   |

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [1]:
import pandas as pd
data = pd.read_csv("Advertising.csv")
data

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np
X = data['TV'].values.reshape([-1, 1])
y = data['sales'].values.reshape([-1, 1])
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [3]:
lr.intercept_

array([7.03259355])

In [4]:
lr.coef_

array([[0.04753664]])

In [5]:
from sklearn.metrics import r2_score

Y_ = lr.predict(X)
r2_score (y,Y_)

0.611875050850071

### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [6]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
SE_b0

0.4578429402734785

In [7]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
b1 = (sigma2/ Sxx)
a = np.sqrt(b1)
a

0.0026906071877968707

Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [8]:
za = 7.03259355 - 2*SE_b0
ze = 7.03259355 + 2*SE_b0
print ( za, ze)

6.116907669453043 7.948279430546957


In [9]:
za = 0.04753664 - 2*a
ze = 0.04753664 + 2*a
print ( za, ze)



0.04215542562440626 0.05291785437559374


Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero. 

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [10]:
tb1 = (0.04753664/a)
tb1

17.667625439937986

In [11]:
tb0 = (7.03259355/SE_b0)
tb0

15.360275176022796

La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [12]:
from scipy import stats
import numpy as np
p_b1 = 2*(1 - stats.t.cdf(np.abs(tb1), n-2))


In [13]:
p_b1

0.0

¿Se rechaza la hipótesis nula? ¿Qué significa?

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

## Periodico

In [14]:
from sklearn.linear_model import LinearRegression
import numpy as np
X = data['newspaper'].values.reshape([-1, 1])
y = data['sales'].values.reshape([-1, 1])
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [15]:
lr.intercept_

array([12.35140707])

In [16]:
lr.coef_

array([[0.0546931]])

In [17]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
SE_b0

0.6214201876094345

In [18]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
b1 = (sigma2/ Sxx)
a = np.sqrt(b1)
a

0.016575721876358165

In [19]:
za = 12.35140707 - 2*SE_b0
ze = 12.35140707 + 2*SE_b0
print ( za, ze)

11.108566694781132 13.594247445218869


In [20]:
za = 0.0546931 - 2*a
ze = 0.0546931 + 2*a
print ( za, ze)

0.021541656247283672 0.08784454375271633


In [21]:
tb1 = (0.0546931/a)
tb1

3.299590835799941

In [22]:
tb0 = (12.35140707/SE_b0)
tb0

19.876095621410546

In [23]:
from scipy import stats
import numpy as np
p_b1 = 2*(1 - stats.t.cdf(np.abs(tb1), n-2))
p_b1

0.0011481955116945386

## Radio

In [54]:
from sklearn.linear_model import LinearRegression
import numpy as np
X = data['radio'].values.reshape([-1, 1])
y = data['sales'].values.reshape([-1, 1])
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [55]:
lr.intercept_

array([9.3116381])

In [56]:
lr.coef_

array([[0.20249578]])

In [57]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
SE_b0

0.5629004962718711

In [58]:
n = len(X)
x_mean = np.mean(X)
y_pred = lr.predict(X)
residuals = y - y_pred
sigma2 = np.sum(residuals**2) / (n - 2) 
Sxx = np.sum((X - x_mean)**2)
SE0 =  sigma2 * (1/n + (x_mean**2) / Sxx)
SE_b0 = np.sqrt(SE0)
b1 = (sigma2/ Sxx)
a = np.sqrt(b1)
a

0.020411306360090635

In [59]:
za = 9.3116381 - 2*SE_b0
ze = 9.3116381 + 2*SE_b0
print ( za, ze)

8.185837107456258 10.437439092543741


In [60]:
za = 0.20249578 - 2*a
ze = 0.20249578 + 2*a
print ( za, ze)

0.16167316727981873 0.24331839272018124


In [61]:
tb1 = (0.20249578/a)
tb1

9.920765306621012

In [62]:
tb0 = (9.3116381/SE_b0)
tb0

16.54224531985959

In [63]:
from scipy import stats
import numpy as np
p_b1 = 2*(1 - stats.t.cdf(np.abs(tb1), n-2))
p_b1

0.0

## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [26]:
import statsmodels.api as sm
X = np.hstack([
    np.ones([n,1]), 
    data['TV'].values.reshape([-1, 1]), 
    data['radio'].values.reshape([-1, 1]),
    data['newspaper'].values.reshape([-1, 1])
])
Y = data['sales'].values.reshape([-1, 1])

ols = sm.OLS(Y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 28 Aug 2025   Prob (F-statistic):           1.58e-96
Time:                        16:58:28   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
x1             0.0458      0.001     32.809      0.000       0.043       0.049
x2             0.1885      0.009     21.893      0.000       0.172       0.206
x3            -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
import statsmodels.api as sm
a = data['TV'].values.reshape([-1, 1])
b = data['radio'].values.reshape([-1, 1])
X = np.hstack([
    np.ones([n,1]), 
    a, 
    b,
    a*b)
])
Y = data['sales'].values.reshape([-1, 1])

ols = sm.OLS(Y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.968
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                     1963.
Date:                Thu, 28 Aug 2025   Prob (F-statistic):          6.68e-146
Time:                        17:36:35   Log-Likelihood:                -270.14
No. Observations:                 200   AIC:                             548.3
Df Residuals:                     196   BIC:                             561.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.7502      0.248     27.233      0.000       6.261       7.239
x1             0.0191      0.002     12.699      0.000       0.016       0.022
x2             0.0289      0.009      3.241      0.001       0.011       0.046
x3             0.0011   5.24e-05     20.727      0.000       0.001       0.001
==============================================================================
Omnibus:                      128.132   Durbin-Watson:                   2.224
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1183.719
Skew:                          -2.323   Prob(JB):                    9.09e-258
Kurtosis:                      13.975   Cond. No.                     1.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?

In [31]:
import statsmodels.api as sm
a = data['TV'].values.reshape([-1, 1])
b = data['radio'].values.reshape([-1, 1])
c = data['newspaper'].values.reshape([-1, 1])
X = np.hstack([
    np.ones([n,1]), 
    a, 
    b,
    c,
    a*b,
    a*c,
    b*c
])
Y = data['sales'].values.reshape([-1, 1])

ols = sm.OLS(Y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     993.3
Date:                Thu, 28 Aug 2025   Prob (F-statistic):          3.68e-142
Time:                        17:43:54   Log-Likelihood:                -267.49
No. Observations:                 200   AIC:                             549.0
Df Residuals:                     193   BIC:                             572.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.4602      0.318     20.342      0.000       5.834       7.087
x1             0.0203      0.002     12.633      0.000       0.017       0.024
x2             0.0229      0.011      2.009      0.046       0.000       0.045
x3             0.0170      0.010      1.691      0.092      -0.003       0.037
x4             0.0011   5.72e-05     19.930      0.000       0.001       0.001
x5         -7.971e-05   3.58e-05     -2.227      0.027      -0.000   -9.12e-06
x6            -0.0001      0.000     -0.464      0.643      -0.001       0.000
==============================================================================
Omnibus:                      111.385   Durbin-Watson:                   2.222
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              767.483
Skew:                          -2.046   Prob(JB):                    2.20e-167
Kurtosis:                      11.681   Cond. No.                     3.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Al hacer la regresión con todos los factores a la vez podemos ver que el periodico 

## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3

## Addendum

Para calcular los *p-values* de los parámetros sin `statsmodels`:
1. Calcular RSS
2. Calcular RSE
3. `var_beta = np.linalg.inv(X.T @ X) * rse**2` (X con columna de intercepto)
4. `std_beta = np.sqrt(var_beta.diagonal())` El orden de los valores corresponde al orden de los factores en las columnas de la matriz $X$.
5. Calcular *estadístico t*
6. Calcular *p-value*